version: '2'

services:

#-------------------------------------------------------------------
# WINE
#-------------------------------------------------------------------
  wine:
    build:
      context: .
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - WINE_MONO_VERSION=${WINE_MONO_VERSION}
      - WINE_GECKO_VERSION=${WINE_GECKO_VERSION}
    networks:
      - backend

#-------------------------------------------------------------------
# NETWORK SETUP
#-------------------------------------------------------------------
networks:
  backend:
    driver: "bridge"

#-------------------------------------------------------------------
# VOLUME SETUP
#-------------------------------------------------------------------
volumes:
  wine:
    driver: "local"